# Generated by Django 4.1.7 on 2023-04-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=100)),
                ('Package', models.IntegerField()),
                ('Days', models.IntegerField()),
                ('Image', models.ImageField(upload_to='')),
                ('Start_date', models.IntegerField()),
                ('End_date', models.IntegerField()),
                ('Hotel_name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
