# Generated by Django 4.1.7 on 2023-04-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_alter_places_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='End_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='places',
            name='Start_date',
            field=models.DateField(),
        ),
    ]
